version: "3"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - ngx_todo:/var/lib/postgresql/data

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_HOST=postgres
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  ngx_todo:
